version: "3.9"
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: baller
      POSTGRES_PASSWORD: ball-is-life
      POSTGRES_DB: ballplayer
      PG_DATA: /var/lib/postgresql/data
    ports:
        - "5432:5432"
    volumes:
        - ballapidb:/var/lib/postgresql/data

volumes:
  ballapidb:
