name: Deploy workflow
on:
  workflow_run:
    workflows: [Test workflow]
    # branches: [main, develop]
    branches: [main]
    types: [completed]

jobs:
  deploy_prod:
    runs-on: ubuntu-18.04
    if: github.event.workflow_run.conclusion == 'success' && github.ref_name == 'main'
    steps:
      - name: Send a request to Render.com
        run: curl ${{ secrets.RENDER_WERBHOOK_URL_MAIN }}

  # deploy_develop:
  #   runs-on: ubuntu-18.04
  #   if: github.event.workflow_run.conclusion == 'success' && github.ref_name == 'develop'
  #   steps:
  #     - name: Send a request to Render.com
  #       run: curl ${{ secrets.RENDER_WERBHOOK_URL_DEVELOP }}
